# TOML file for fpm as described at https://fpm.fortran-lang.org/en/spec/manifest.html
name = "M_slices"
version = "0.1.0"
license = "MIT"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "Copyright 2020, John S. Urban"
description = " produce basic slice plot on POSIX systems with X11 Windows"
categories = ["graphics"]
keywords = ["fortran", "plot", "graph" ]
homepage = "https://github.com/urbanjost/M_slices.git"

[build]
module-naming = true
#auto-executables = true
auto-tests = true
auto-examples = true
#link = ["wif97" ]

[dependencies]
M_draw       =  {  git  =  "https://github.com/urbanjost/M_draw.git"       }
M_io         =  {  git  =  "https://github.com/urbanjost/M_io.git"         }
M_strings    =  {  git  =  "https://github.com/urbanjost/M_strings.git"    }
M_kracken95  =  {  git  =  "https://github.com/urbanjost/M_kracken95.git"  }
M_framework  =  {  git  =  "https://github.com/urbanjost/M_framework.git"  }
#M_draw       =  {  namespace = "GPF" }
#M_io         =  {  namespace = "GPF" }
#M_strings    =  {  namespace = "GPF" }
#M_kracken95  =  {  namespace = "GPF" }
#M_framework = {namespace = "GPF"}

[[executable]]
name = "slices"
source-dir = "app/"
main = "slice.f90"

